In [72]:
import numpy as np

l = ('10;'*10).split(';')
print(l)

a = np.array(range(20))
#print(a)

x = np.array([1,2,3,4,5,6])
y = np.array([2,3,4,5,6,7])

#Поэлементные операции
print(x+y)
print(x**y)
print(x/y, end='\n\n')

#arange
r = np.arange(10)
print(r)
r = np.arange(0,101,17)
print(r)
print(type(r))

#Генерация векторов и матриц
print('\n',np.full(10,2))
print(np.full(12, 'qq'))
#для матрицы 4x16
print(np.full([4,16],2))

#Конкатенациия. !данные в кортежах
a = np.full(10,1)
b = np.full(6,6)
c = np.concatenate((a,b))
print(c)

#Random и перемешивание
import random
a = np.arange(1,20)
random.shuffle(a)
print(a)

#Reshape
print('\nreshape')
a = np.arange(10)
a.shape
print(a.reshape(2,5))
print(a.reshape(5,2))

#Transpone
print('\ntransp')
a = np.arange(12)
a = a.reshape(2,6)
a = a.T
print(a)

#Ravel Разглаживание
print('\nravel')
a = np.arange(12)
a = a.reshape(2,2,3)
print(a)
a = a.ravel()
print(a)

#Reshape разглаживание
print('\nreshape разглаживание')
a = np.arange(12)
a = a.reshape(2,2,3)
print('вектор')
print(a.reshape(12))
print('матрица из 1 строки')
print(a.reshape(1,12))

#Матрицы
a = np.zeros(10)
print('\n', a)

a = np.eye(5)
print('\n',a)

a = np.diag([0,1,2,3])
print('\n',a)

a = np.diag(np.arange(0,10))
print('\n',a)

a = np.random.random(22)
print('\n',a)

#linspace
#делит диапазон на заданное количество отсчетов
#границы входят в итоговый диапазон
a = np.linspace(1,10,101)
print('\n',a)
print(len(a))

['10', '10', '10', '10', '10', '10', '10', '10', '10', '10', '']
[ 3  5  7  9 11 13]
[     1      8     81   1024  15625 279936]
[0.5        0.66666667 0.75       0.8        0.83333333 0.85714286]

[0 1 2 3 4 5 6 7 8 9]
[ 0 17 34 51 68 85]
<class 'numpy.ndarray'>

 [2 2 2 2 2 2 2 2 2 2]
['qq' 'qq' 'qq' 'qq' 'qq' 'qq' 'qq' 'qq' 'qq' 'qq' 'qq' 'qq']
[[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]
[1 1 1 1 1 1 1 1 1 1 6 6 6 6 6 6]
[16 12  1 19 17  7  2  9  6 15  5 14  4 13 18  8  3 11 10]

reshape
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

transp
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]

ravel
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape разглаживание
вектор
[ 0  1  2  3  4  5  6  7  8  9 10 11]
матрица из 1 строки
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [[1. 0. 0. 0. 0.